<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Eagle Soft Switch : Admin</title>
<link href="css/style.css" rel="stylesheet" type="text/css" />
</head>

<body>
<table width="100%" height="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td align="center" valign="middle"><table border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td class="admin"><table width="100%" border="0" cellspacing="0" cellpadding="8" class="logintable">
          <tr>
            <td>Username</td>
            <td><input type="text" name="textfield" id="textfield" class="txt2"></td>
          </tr>
          <tr>
            <td>Password</td>
            <td><input type="text" name="textfield2" id="textfield2" class="txt2"></td>
          </tr>
          <tr>
            <td>&nbsp;</td>
            <td><a href="customer"><img src="images/login.gif" width="75" height="25"></a></td>
          </tr>
        </table></td>
      </tr>
    </table></td>
  </tr>
</table>
</body>
</html>
