				<h2>Add CID Group</h2>
                    <table border="0" cellspacing="0" cellpadding="8" width="100%" id="form-add">
                      <tr>
                        <td width="15%">CID Group Name</td>
                        <td width="38%"><input name="textfield" type="text" class="txt1" id="textfield"></td>
                        <td width="50%">&nbsp;</td>
                      </tr>
                      <tr>
                        <td>&nbsp;</td>
                        <td><table width="96%" border="0" cellspacing="0" cellpadding="0">
                          <tr>
                            <td align="left"><input name="textfield5" type="button" value="Add" class="btn" id="add_group"></td>
                            <td align="right"><input name="textfield5" type="button" value="Clear" class="btn" id="clear-form"></td>
                          </tr>
                        </table>
                        </td>
                        <td>&nbsp;</td>
                      </tr>
                    </table>
                    <p>&nbsp;</p>
                    <table width="100%" border="0" class="filterbox">
                    <tr>
                    <td width="2%" valign="middle">&nbsp;</td>
                    <td width="15%" valign="middle"><input name="groupname" type="text" class="txt1" id="groupname"></td>
                    <td width="1%">&nbsp;</td>
                    <td width="72%" valign="middle"><input name="textfield5" type="button" value="Apply Filter" class="btn" id="search" style="width:95px;"></td>
                    </tr>
                    </table>
                    <table width="100%" border="1" cellpadding="5" cellspacing="0" bordercolor="#c4c4c4" style="border-collapse:collapse;" id="list-view">
                    <thead>
                      <tr>
                        <td bgcolor="#dedede" width="28%"><strong>ID</strong></td>
                        <td bgcolor="#dedede" width="28%"><strong>DID Group Name</strong></td>
                        <td bgcolor="#dedede" width="29%"><strong>Creation Date</strong></td>
                        <td bgcolor="#dedede" width="15%"><strong>Action</strong></td>
                      </tr>
                     </thead>
                     <tbody></tbody>
                    </table>
                    <div id="popup_block" class="popup_block">
                    <div>
				    	<h1 style="width:510px; margin-bottom:15px;">Edit item</h1>
				        	<div class="popup_content"></div>
				    </div>
                    </div>