                    <table border="0" cellspacing="0" cellpadding="8" id="form-edit">
                      <tr>
                        <td style="vertical-align:top;">CID Number</td>
                        <td width="50%"><textarea name="cid" cols="" rows="" class="txtbox2"><?php echo $this->o_Item->cid;?></textarea><br><span class="smalltxt">Note:80412340210-80412340218 would add all CID's between the range, whereas CIDs separated by a comma e.g. 80412340210, 80412340212, 80412340214 would only add the individual CID listed.</span></td>
                        <td width="20%">&nbsp;</td>
                      </tr>
                      <tr>
                      <td>CID Group</td>
                        <td>
                        	<?php echo $this->formSelect('group', $this->o_Item->outbound_cid_group	, array('class'=>"selectbox1"), $this->a_GroupAs)?>                        	
                        </td>
                        <td width="10%">&nbsp;</td>
                        </tr>
                      <tr>
                        <td>Activated</td>
                        <td colspan="2"><input name="active" type="radio" value="1" id="active_1"<?php if($this->o_Item->activated):?> checked="checked"<?php endif;?>> <label for="active_1">Yes</label> &nbsp;&nbsp; <input name="active" type="radio" value="0" id="active_0"<?php if(!$this->o_Item->activated):?> checked="checked"<?php endif;?>> <label for="active_0">No</label></td>                        
                      </tr>
                      <tr>
                      <td>&nbsp;</td>
                      <td><input name="textfield5" type="submit" value="Save" class="btn" id="save" onclick="OUTBOUND.save()">
                      <input name="textfield5" type="submit" value="Cancel" class="btn" id="close-popup" style="float:right;"></td>
                      <td width="10%">&nbsp;</td>
                      </tr>
                      <input type="hidden" name="id" value="<?php echo $this->o_Item->id;?>">
                    </table>