<h2>Add CID</h2>
                    <table border="0" cellspacing="0" cellpadding="8" width="100%" id="form-add">
                      <tr>
                        <td width="15%" style="vertical-align:top;">CID Number</td>
                        <td width="20%"><textarea name="cid" cols="" rows="" class="txtbox2"></textarea><br><span class="smalltxt">Note:80412340210-80412340218 would add all CID's between the range, whereas CIDs separated by a comma e.g. 80412340210, 80412340212, 80412340214 would only add the individual CID listed.</span></td>
                        <td width="65%">&nbsp;</td>
                      </tr>
                      <tr>
                      <td>CID Group</td>
                        <td>
                        	<?php echo $this->formSelect('group', '', array('class'=>"selectbox1"), $this->a_GroupAs)?>                        	
                        </td>
                        <td>&nbsp;</td>
                        </tr>
                      <tr>
                        <td>Activated</td>
                        <td colspan="4"><input name="active" type="radio" value="1" id="active_1" checked="checked"> <label for="active_1">Yes</label> &nbsp;&nbsp; <input name="active" type="radio" value="0" id="active_0"> <label for="active_0">No</label></td>
                        <td>&nbsp;</td>
                      </tr>
                      <tr>
                      <td>&nbsp;</td>
                      <td><input name="textfield5" type="button" value="Add" class="btn" id="add"><input name="textfield5" type="submit" value="Clear" class="btn" id="clear-form" style="float:right;"></td>
                      <td>&nbsp;</td>
                      
                      </tr>
                      
                    </table>
                    <p>&nbsp;</p>
                    <table width="100%" border="0" class="filterbox">
                    <tr>
                    <td width="2%" valign="middle">&nbsp;</td>
                    <td width="15%" valign="middle"><input name="cid" type="text" class="txt1" id="cid"></td>
                    <td width="1%">&nbsp;</td>
                    <td width="72%" valign="middle"><input name="textfield5" type="button" value="Apply Filter" class="btn" id="search" style="width:95px;"></td>
                    </tr>
                    </table>
                    <table width="100%" border="1" cellpadding="5" cellspacing="0" bordercolor="#c4c4c4" style="border-collapse:collapse;" id="list-view">
                      <thead>
                      <tr>
                        <td bgcolor="#dedede" width="28%"><strong>CID Number</strong></td>
                        <td bgcolor="#dedede" width="28%"><strong>CID Group</strong></td>
                        <td bgcolor="#dedede" width="29%"><strong>Status</strong></td>
                        <td bgcolor="#dedede" width="15%"><strong>Action</strong></td>
                      </tr>
                      </thead>
                      <tbody></tbody>                      
                    </table>
                    <div id="popup_block" class="popup_block">
                    <div>
				    	<h1 style="width:510px; margin-bottom:15px;">Edit item</h1>
				        	<div class="popup_content"></div>
				    </div>
                    </div>