<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<?php echo $this->headTitle();?>
<?php echo $this->headLink() ?>
<script type="text/javascript">
	var sz_PublicHost = '<?php echo $this->sz_PublicHost;?>';
</script>
<?php echo $this->headScript() ?>
    <script type="text/javascript">
		$(function() {
			$("#tree").treeview({
				collapsed: true,
				animated: "medium",
				control:"#sidetreecontrol",
				persist: "location"
			});
		});
	</script>
<script type="text/javascript">
        $(document).ready(function() {
            try{
            $(".itemDetails").EnableMultiField();
            }catch(e)
            {}
        });
</script>
  <!--script for add more input ends-->
</head>

<body>
<table width="100%" height="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td align="center" valign="top"><table width="100%" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td width="20" height="20"><img src="<?php echo $this->sz_PublicHost?>/images/cor1.png" width="20" height="20"></td>
        <td class="br-top">&nbsp;</td>
        <td width="20"><img src="<?php echo $this->sz_PublicHost?>/images/cor2.png" width="20" height="20"></td>
      </tr>
      <tr>
        <td class="br-left">&nbsp;</td>
        <td bgcolor="#FFFFFF"><table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td class="header"><table width="100%" border="0" cellspacing="0" cellpadding="10">
              <tr>
                <td><img src="<?php echo $this->sz_PublicHost?>/images/logo.png" width="336" height="71"></td>
                <td align="right" valign="top"><a href="index.php" title="Home">Home</a>   &nbsp;&nbsp;|&nbsp;&nbsp;   <a href="#" title="Sign Out">Sign Out</a></td>
              </tr>
            </table></td>
            </tr>
          <tr>
            <td >
            <table width="100%" border="0" cellpadding="0" cellspacing="0" id="searchFieldsTable">
              <tr>
                <td align="left" valign="top" class="sidebar">
					<?php echo $this->layout()->render('leftmenu');?>
                </td>
                <td valign="top" align="left"  id="content" class="key">
                <?php echo $this->layout()->content; ?>
                </td>
              </tr>
            </table></td>
            </tr>
        </table></td>
        <td class="br-right">&nbsp;</td>
      </tr>
      <tr>
        <td><img src="<?php echo $this->sz_PublicHost?>/images/cor3.png" width="20" height="20"></td>
        <td class="br-bottom">&nbsp;</td>
        <td><img src="<?php echo $this->sz_PublicHost?>/images/cor4.png" width="20" height="20"></td>
      </tr>
    </table></td>
  </tr>
</table>
</body>
</html>
